# .streamlit/secrets.toml

[tableau]
token_name = "streamlit.app"
token_secret = "12345"
server_url = "https://tableau.pupuk-indonesia.com/#/views/BahanBakuCommancenter/DashboardDAP?:iid=2"
site_id = "streamlitexample"  # in your site's URL behind the server_url
